### ISSUE TITLE
Pandocomatic install on Windows 10

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#76] opened 2019-07-21 08:04 UTC
Hi Huub,

I am not a windows user, but was asked how to use Pandoc+pandocomatic on windows. I just tried to install using the chocolatey package manager (like apt or homebrew).

```
choco install pandoc
choco install ruby
gem install pandocomatic
```

after restarting the terminal, pandoc and ruby are callable, but pandocomatic gives an error:

```
PS C:\Users\cog1> pandoc -v
pandoc.exe 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: C:\Users\cog1\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

PS C:\Users\cog1> ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]

PS C:\Users\cog1> pandocomatic -v
Traceback (most recent call last):                                                                                           
 17: from C:/tools/ruby26/bin/pandocomatic:23:in `<main>'                                                            
 16: from C:/tools/ruby26/bin/pandocomatic:23:in `load'                                                                
 15: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.4/bin/pandocomatic:2:in `<top (required)>'      
  14: from C:/tools/ruby26/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                             
13: from C:/tools/ruby26/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                      
      
12: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.4/lib/pandocomatic/pandocomatic.rb:19:in `<top (required)>'                                                                                                                
11: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.4/lib/pandocomatic/pandocomatic.rb:29:in `<module:Pandocomatic>'                                                                                                           
10: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.4/lib/pandocomatic/pandocomatic.rb:29:in `require_relative'                                                                                                                 
9: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.4/lib/pandocomatic/cli.rb:19:in `<top (required)>'                                                                                                                      
8: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.4/lib/pandocomatic/cli.rb:23:in `<module:Pandocomatic>'                                                                                                                  
7: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.4/lib/pandocomatic/cli.rb:23:in `require_relative'                                                                                                                    
 6: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.4/lib/pandocomatic/configuration.rb:19:in `<top (required)>'                                                                                                                
5: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.4/lib/pandocomatic/configuration.rb:22:in `<module:Pandocomatic>'                                                                                                           
4: from C:/tools/ruby26/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                              
3: from C:/tools/ruby26/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                              
2: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/paru-0.3.2.1/lib/paru/pandoc.rb:25:in `<top (required)>'               
1: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/paru-0.3.2.1/lib/paru/pandoc.rb:81:in `<module:Paru>'    
 C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/paru-0.3.2.1/lib/paru/pandoc.rb:229:in `<class:Pandoc>': undefined method `[]' for nil:NilClass (NoMethodError)                                                                                        

```

**Comment by htdebeer** [comment] 2019-07-21 09:02
According to the stack trace, the problem is with paru, in `lib/paru/pandoc.rb` at line

```Ruby
version = version_string.match(/pandoc (\d+\.\d+.*)$/)[1]
```

Looking at your output for `pandoc -v`, I do see this RegExp does not match the output of `pandoc -v` on window.

I do not actively support any operating systems except GNU/Linux, but I can rewrite this regular expression to accept the output of `pandoc -v` on Windows. Give me a day or so.

**Comment by htdebeer** [comment] 2019-07-21 09:24
I've created a fix in paru and updated pandocomatic. The fix is in paru 0.3.2.2 and pandocomatic 0.2.5.5.

Note. Someone using Windows should test this.

**Closed by htdebeer** 2019-07-21 09:24 UTC
Labels: windows-trouble

**Comment by iandol** [comment] 2019-07-28 11:57
Hi Huub, thank you, just to confirm this fix worked. There are more errors which I’ll try to work out when I can. I know you don’t officially support Windows, but it is worth detailing so other users who use windows may contribute fixes...

**Comment by htdebeer** [comment] 2019-07-28 14:03
You're right, being transparent about this might be better. I'll update the README.
