### ISSUE TITLE
pandocomatic has stopped working

### ISSUE THREAD

**Issue by atanasj** [htdebeer/pandocomatic#77] opened 2019-09-12 22:31 UTC
Hi,

`pandocomatic` has stopped working... This happened after I had updated `paru`, however I'm not sure if the two are related. See the error for the `cli` below: 

```bash
| => pandocomatic --help
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
Traceback (most recent call last):
        12: from /Users/atanas/.rbenv/versions/2.5.1/bin/pandocomatic:23:in `<main>'
        11: from /Users/atanas/.rbenv/versions/2.5.1/bin/pandocomatic:23:in `load'
        10: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/bin/pandocomatic:3:in `<top (required)>'
         9: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/pandocomatic.rb:58:in `run'
         8: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:42:in `parse'
         7: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `parse_options'
         6: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `new'
         5: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:75:in `initialize'
         4: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:135:in `load'
         3: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `configure'
         2: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `each'
         1: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `block in configure'
/Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `merge': no implicit conversion of nil into Hash (TypeError)
```

Please let me know if you need any more info. 

Cheers,
Atanas.

**Comment by atanasj** [comment] 2019-09-13 11:26
Hi, 

Sorry, but how do I produce a minimal example? I cannot seem to attached an `.md` file so I've attached a `.txt` version: [test_error.txt](https://github.com/htdebeer/pandocomatic/files/3609811/test_error.txt). I got the following error: 

```bash
| => pandocomatic -i test_error.md -o test_error.pptx
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
Traceback (most recent call last):
        12: from /Users/atanas/.rbenv/versions/2.5.1/bin/pandocomatic:23:in `<main>'
        11: from /Users/atanas/.rbenv/versions/2.5.1/bin/pandocomatic:23:in `load'
        10: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/bin/pandocomatic:3:in `<top (required)>'
         9: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/pandocomatic.rb:58:in `run'
         8: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:42:in `parse'
         7: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `parse_options'
         6: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `new'
         5: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:75:in `initialize'
         4: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:135:in `load'
         3: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `configure'
         2: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `each'
         1: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `block in configure'
/Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `merge': no implicit conversion of nil into Hash (TypeError)
```

Relevant version numbers:

```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95

pandoc 2.7.3
paru 0.3.2.4
pandocomatic 0.2.5.5
```

Also, when typing `gem list` `pandocomatic` is not shown. However when checking my `gems` folder, I have two versions: `pandocomatic-0.2.4.2` and `pandocomatic-0.2.5.5`. When running `pandocomatic --version` I got the following error: 
```bash
| => pandocomatic --version
Traceback (most recent call last):
	2: from /Users/atanas/.rbenv/versions/2.5.1/bin/pandocomatic:23:in `<main>'
	1: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/atanas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem pandocomatic (>= 0.a) with executable pandocomatic (Gem::GemNotFoundException)
```
I then tried installing via `gem install pandocomatic` and got the following error: 

```bash
| => gem install pandocomatic
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted @ apply2files - /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/bin/pandocomatic
```

So, after install via `sudo`, `pandocomatic` was then show when running the `gem list` command, however when running `pandocomatic --version` I get the following error:

```bash
| => pandocomatic --version
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
Traceback (most recent call last):
	12: from /Users/atanas/.rbenv/versions/2.5.1/bin/pandocomatic:23:in `<main>'
	11: from /Users/atanas/.rbenv/versions/2.5.1/bin/pandocomatic:23:in `load'
	10: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/bin/pandocomatic:3:in `<top (required)>'
	 9: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/pandocomatic.rb:58:in `run'
	 8: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:42:in `parse'
	 7: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `parse_options'
	 6: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `new'
	 5: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:75:in `initialize'
	 4: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:135:in `load'
	 3: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `configure'
	 2: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `each'
	 1: from /Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `block in configure'
/Users/atanas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `merge': no implicit conversion of nil into Hash (TypeError)
```

Please let me know what else I can do. Thanks.

**Comment by htdebeer** [comment] 2019-09-13 12:39
Thanks for the detailed info. Can you also send me the contents of the "pptx" template you are using in the test file?

And could you try to remove "paru" all together and then install paru version 0.3.2.2 and see if that one works?

**Comment by htdebeer** [comment] 2019-09-21 10:01
I have been unable to reproduce the issue. Please answer the questions asked in the previous message.

Closing this issue for now.

**Comment by atanasj** [comment] 2019-09-22 23:28
Sorry for my late reply... I had previously reinstalled an earlier version of `paru` and the same issue occurred. I have included an example of a test file (with `.txt` extension added): [test_error.md.txt](https://github.com/htdebeer/pandocomatic/files/3640271/test_error.md.txt). 

I have updated to `ruby 2.6.4`. I then reinstalled `pandocmomatic`:

```bash
| => gem install pandocomatic
Fetching pandocomatic-0.2.5.5.gem
Fetching paru-0.3.2.4.gem
Fetching optimist-3.0.0.gem
Successfully installed paru-0.3.2.4
Successfully installed optimist-3.0.0
Successfully installed pandocomatic-0.2.5.5
Parsing documentation for paru-0.3.2.4
Installing ri documentation for paru-0.3.2.4
Parsing documentation for optimist-3.0.0
Installing ri documentation for optimist-3.0.0
Parsing documentation for pandocomatic-0.2.5.5
Installing ri documentation for pandocomatic-0.2.5.5
Done installing documentation for paru, optimist, pandocomatic after 1 seconds
3 gems installed
```
However: 

```bash
| => pandocomatic --help
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
Traceback (most recent call last):
	12: from /Users/atanas/.rbenv/versions/2.6.4/bin/pandocomatic:23:in `<main>'
	11: from /Users/atanas/.rbenv/versions/2.6.4/bin/pandocomatic:23:in `load'
	10: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/bin/pandocomatic:3:in `<top (required)>'
	 9: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/pandocomatic.rb:58:in `run'
	 8: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:42:in `parse'
	 7: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `parse_options'
	 6: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `new'
	 5: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:75:in `initialize'
	 4: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:135:in `load'
	 3: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `configure'
	 2: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `each'
	 1: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `block in configure'
/Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `merge': no implicit conversion of nil into Hash (TypeError)
```

Despite: 

```bash
| => gem list

*** LOCAL GEMS ***

bigdecimal (1.4.4, default: 1.4.1)
bundler (2.0.2, default: 1.17.3)
cmath (default: 1.0.0)
csv (3.1.1, default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
etc (default: 1.0.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (1.2.0, default: 1.1.0)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
io-console (0.4.8, default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (2.2.0, default: 2.1.0)
logger (1.4.1, default: 1.3.0)
matrix (default: 0.1.0)
minitest (5.11.3)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
openssl (default: 2.1.2)
optimist (3.0.0)
ostruct (default: 0.1.0)
pandocomatic (0.2.5.5)
paru (0.3.2.4)
power_assert (1.1.5)
prime (default: 0.1.0)
psych (default: 3.1.0)
rake (12.3.3)
rdoc (6.2.0, default: 6.1.2)
rexml (3.2.2, default: 3.1.9)
rss (0.2.8, default: 0.2.7)
rubygems-update (3.0.6)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.3.3)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```

Not sure if this would be helpful or not: 

```bash
| => gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.6
  - RUBY VERSION: 2.6.4 (2019-08-28 patchlevel 104) [x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/atanas/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /Users/atanas/.rbenv/versions/2.6.4/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/atanas/.rbenv/versions/2.6.4/bin
  - SPEC CACHE DIRECTORY: /Users/atanas/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/atanas/.rbenv/versions/2.6.4/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-18
  - GEM PATHS:
     - /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0
     - /Users/atanas/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/atanas/.rbenv/versions/2.6.4/bin
     - /usr/local/Cellar/rbenv/1.1.2/libexec
     - /Users/atanas/git/GCP-STT/google-cloud-sdk/bin
     - /Users/atanas/.nvm/versions/node/v12.4.0/bin
     - /private/var/folders/77/7ht3td2j1vb00csyp1l4wlv40000gn/T/build-openssl@1.1/opt/openssl@1.1/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/atanas/.rbenv/shims
     - /usr/local/opt/sqlite/bin
     - /Users/atanas/perl5/perlbrew/bin
     - /Users/atanas/perl5/perlbrew/perls/perl-5.26.1/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /usr/local/ActivePerl-5.24/bin
     - /Users/atanas/bin
     - /usr/local/opt/sphinx-doc/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/local/opt/libxml2/bin
     - /usr/local/opt/curl/bin
     - Users/atanas/bin
     - /usr/local/opt/coreutils/libexec/gnubin
     - /Users/atanas/.pandoc/filters
     - /Library/TeX/texbin
     - /usr/local/MacGPG2/bin
     - /usr/local/share/dotnet
     - /opt/X11/bin
     - ~/.dotnet/tools
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/atanas/.local/bin
```
I have included the relevant template from my `pandocomatic.yaml`: 

```yaml
#-----------------------------------------------------------------------------
  refs:
    setup: [] #runs a general script to rename or copy files before anything is run
    preprocessors: [] #runs a script on the markdown file itself
    pandoc:
      standalone: true #create complete document
      filter: 'pandoc-citeproc'  #run filter to process citations
      bibliography: "MyLib.bib" #bibtex file, default search path will be your pandoc data-dir
      csl: "csl/apa-old-doi-prefix.csl" #CSL style file, in the csl/ folder of pandoc data-dir
      lua-filter: 'filters/pagebreak.lua' # lua filter to implement page break after \newpage or \pagebreak
    metadata:
      link-citations: True
      notes-after-punctuation: False
    postprocessors: [] #runs on the output file (unless it is binary like docx)
    cleanup: [] #general cleanup script
#-----------------------------------------------------------------------------
  pptx:
  extends: ['refs']
  pandoc:
    from: markdown
    to: pptx
#-----------------------------------------------------------------------------
```

I hope this helps... Thanks again.

**Comment by htdebeer** [comment] 2019-09-23 04:53
I think this helps. If I understand your reply correctly, pandocomatic already crashes when running "pandocomatic --help"? 

If so, I have trouble reproducing the issue on my GNU/Linux machines. I setup the same version you used, with pandoc 2.7.3, ruby 2.6.4, pandocomatic 0.2.5.5, and paru 0.3.2.4, but it still works.


Because paru is the only thing that has changes in the past two weeks, it is the likely culprit. Can you uninstall paru and install version 0.3.2.3 via 

    gem uninstall paru
    gem install paru -v 0.3.2.3

and report back if this does not have the issue?

**Comment by atanasj** [comment] 2019-09-30 02:22
Sorry for the tardy reply… Okay, so this is what I got: 

```bash
| ~ @ uroboros (atanas)
| =>  gem uninstall paru && gem install paru -v 0.3.2.3

You have requested to uninstall the gem:
	paru-0.3.2.3

pandocomatic-0.2.5.5 depends on paru (~> 0.3.2, >= 0.3.2.2)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Remove executables:
	pandoc2yaml.rb, do-pandoc.rb

in addition to the gem? [Yn]  Y
Removing pandoc2yaml.rb
Removing do-pandoc.rb
Successfully uninstalled paru-0.3.2.3
Fetching paru-0.3.2.3.gem
Successfully installed paru-0.3.2.3
Parsing documentation for paru-0.3.2.3
Installing ri documentation for paru-0.3.2.3
Done installing documentation for paru after 0 seconds
1 gem installed
________________________________________________________________________________
| ~ @ uroboros (atanas)
| => gem install pandocomatic
Successfully installed pandocomatic-0.2.5.5
Parsing documentation for pandocomatic-0.2.5.5
Done installing documentation for pandocomatic after 0 seconds
1 gem installed
________________________________________________________________________________
| ~ @ uroboros (atanas)
| => pandocomatic --help
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
Traceback (most recent call last):
	12: from /Users/atanas/.rbenv/versions/2.6.4/bin/pandocomatic:23:in `<main>'
	11: from /Users/atanas/.rbenv/versions/2.6.4/bin/pandocomatic:23:in `load'
	10: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/bin/pandocomatic:3:in `<top (required)>'
	 9: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/pandocomatic.rb:58:in `run'
	 8: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:42:in `parse'
	 7: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `parse_options'
	 6: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/cli.rb:145:in `new'
	 5: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:75:in `initialize'
	 4: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:135:in `load'
	 3: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `configure'
	 2: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:161:in `each'
	 1: from /Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `block in configure'
/Users/atanas/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.5/lib/pandocomatic/configuration.rb:173:in `merge': no implicit conversion of nil into Hash (TypeError)
________________________________________________________________________________
```

I'm really baffled… Thoughts?

**Comment by htdebeer** [comment] 2019-09-30 04:42
As am I. Have you any idea when exactly it stopped working? And if you updated pandoc or pandocomatic around that time? You might try installing a pandocomatic and paru version you used the last time it still worked. That should still work. Unless something external to these two packages has changed in a way we do not understand.

**Comment by htdebeer** [comment] 2019-10-09 15:04
Unable to reproduce issue; need more information.

**Closed by htdebeer** 2019-10-09 15:04 UTC
Labels: bug
