### ISSUE TITLE
Suppress last line: pandocomatic-fileinfo

### ISSUE THREAD

**Issue by jokorn** [htdebeer/pandocomatic#59] opened 2018-08-07 08:56 UTC
Hi htdebeer

Thank you for this amazing tool!
One question: How do I suppress the last line in the output file that looks like the following in PDF documents:

pandocomatic-fileinfo: to: pdf path: ‘draft.md’ created: 2018-08-07 modified: 2018-08-07 ...

Or like this in DOCX:

pandocomatic-fileinfo: from: markdown to: docx path: ‘/Users/jonatank/Dropbox/???’ created: 2018-08-07 modified: 2018-08-07 …
link-citations: false reference-section-title: References notes-after-punctuation: false …

I am using Pandocomatic version 0.2.3.0, paru 0.3.0.1, ruby 2.5.1p57 and pandoc 2.2.3 on OS X High Sierra. Pandoc installed via homebrew and pandocomatic via gem install.

Kind regards

**Comment by jokorn** [comment] 2018-08-07 10:52
Nevermind... I commented out these lines:

output << "\n\n---\n"
output << "pandocomatic-fileinfo:\n"
output << "  from: #{options['from']}\n" if options.has_key? 'from'
output << "  to: #{options['to']}\n" if options.has_key? 'to'
output << "  template: #{options['template']}\n" if options.has_key? 'template'
output << "  path: '#{path}'\n"
output << "  created: #{created_at.strftime '%Y-%m-%d'}\n"
output << "  modified: #{modified_at.strftime '%Y-%m-%d'}\n"
output << "...\n\n" 

in "fileinfo_preprocessor.rb". That solved it.

**Comment by htdebeer** [comment] 2018-08-07 16:11
Jokorn, thanks for submitting your issue.

You can comment these lines out, but you might lose some of the functionality of pandocomatic. In particular the "convert only updated files" function.

Anyway, that line should not have been visible. It is a pandoc metadata YAML block and should not be send to the output at all.

Can you give a minimal example where this issue did occur? A minimal example should at least contain:

- a minimal input file
- the pandocomatic command line invocation converting that input file
- if you're using a template the template definition

Then I can try to reproduce the issue to solve it.

**Comment by jokorn** [comment] 2018-08-07 17:47
Oh, I didn't know that it wasn't supposed to print. I'll see if I can make a minimal reproducible example; might be a couple of days.

**Comment by jokorn** [comment] 2018-08-07 18:59
Already found some time to look at this:

If I create a test.md file like this:

```
---
pandocomatic_:
    use-template:
    - pdf-test
---

# Test header

Test text
```

And the pdf-test specification in pandocomatic.yaml is:

```
settings:
    recursive: false
    follow-symlinks: false
    skip: ['.*', 'pandocomatic.yaml']
templates:
    pdf-test:
        pandoc:
            from: markdown
            to: pdf
```

And I run "pandocomatic -b test.md" in terminal, then the output is:

```
pandoc	--from=markdown \
	--to=latex \
	--output=/Users/user/Desktop/test.pdf
Pandocomatic needed 0.9 seconds to convert 'test.md'.
```

And the resulting PDF includes a HR line followed by "pandocomatic-fileinfo: from: markdown to: pdf path: ‘test.md’ created: 2018- 08-07 modified: 2018-08-07 . . ." 

Same result if I convert from markdown to markdown.

If I instead create another markdown file with a separate YAML header at the bottom and convert directly with pandoc (without pandocomatic), then the YAML header is not printed.

**Comment by htdebeer** [comment] 2018-08-08 08:05
Thanks for your quick reply!

As of yet I am unable to reproduce the issue if I follow your scenario. The only differences between mine and your setup is the pandoc version (I'm using version 2.2), the Ruby version (I'm using version ruby 2.5.0p0) and the operating system (I'm using Linux). These differences seems irrelevant, but I'll try to reproduce the issue with the same version of Ruby and pandoc as well. And if that does not work, I'll try to find a MacOSX machine somewhere to see if that's somehow the culprit.

**Comment by htdebeer** [comment] 2018-08-08 08:32
Using Ruby 2.5.1 neither.

**Comment by htdebeer** [comment] 2018-08-08 11:47
On MacOSX (El Capitan) I am still unable to reproduce the issue.

Something is going wrong and I have no idea why. Do you know of any settings or changes you made to your system that could explain this behavior? 

The `FileInfoPreprocessor` is for every file that is being converted by pandocomatic. But at the same time, the `MetadataPreprocessor` is also run. Will its output also be printed? Can you try the following:

- end your YAML blocks with `...` rather than with `---`. This shouldn't make any difference, but it is good to exclude as a possibility.
- change your template to:

      settings:
        recursive: false
        follow-symlinks: false
        skip: ['.*', 'pandocomatic.yaml']
      templates:
        pdf-test:
          pandoc:
            from: markdown
            to: pdf
          metadata:
            title: Test file
            author: A, Thor
- Can you try the settings file without the `settings` section?
- Can you try an inline template:

      ---
      pandocomatic_:
        pandoc:
           from: markdown
           to: pdf
      ...

      # Test header

      Test text

**Comment by jokorn** [comment] 2018-08-08 19:54
Thanks for the fast reply. And that is weird. Don't know why my system is doing this...

I tried your suggestions:

> end your YAML blocks with ... rather than with ---. This shouldn't make any difference, but it is good to exclude as a possibility.

Didn't make a difference.

> change you template to...

Still a problem and know the metadata is printed as well. See this screenshot from the resulting PDF.

![skaermbillede 2018-08-08 kl 21 29 26](https://user-images.githubusercontent.com/7759201/43860279-7e677f08-9b53-11e8-8a50-50c76b2bdb0f.png)

> Can you try the settings file without the settings section?

Same problem.

> Inline template

Same problem.

I am not really sure how to go from here. It sounds like something is off in my setup since you can't reproduce this. Maybe we should just put this issue on hold until Mac Os X Mojave is released later this year - then I'll do a clean install and see if the issue persists. For now I do not need the extra functionality provided by fileinfo_preprocessor.rb so I can just comment the lines out.

**Comment by jokorn** [comment] 2018-08-08 20:13
I just saw that there was a new version of pandoc available on homebrew and after updating pandoc from 2.2.3 -> 2.2.3.2 the problem is resolved!

**Comment by htdebeer** [comment] 2018-08-08 20:14
Awesome!

**Comment by htdebeer** [comment] 2018-08-08 20:15
Then I probably only tested it on my end with a earlier and later point version than the one you had the issue with :-)

Anyway, I'll close the issue. Thanks for your collaboration.

**Closed by htdebeer** 2018-08-08 20:15 UTC
